// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common {

  /// <summary>Holder for reflection information generated from common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb21tb24ucHJvdG8SBmNvbW1vbiq4AgoPQ29tbW9uRXJyb3JDb2RlEg8K",
            "C0VSUl9TVUNDRVNTEAASFwoKRVJSX0ZBSUxFRBD///////////8BEhUKEEFO",
            "U19DT01NT05fRVJST1IQkE4SHAoXRVJSX01FU1NBR0VfTE9BRF9GQUlMRUQQ",
            "kU4SGgoVRVJSX01FU1NBR0VfTk9UX0ZPVU5EEJJOEhcKEkVSUl9JTlZBTElE",
            "X1VTRVJOTxCTThIZChRFUlJfQ0FOTk9UX0ZJTkRfVVNFUhCUThImCiFFUlJf",
            "RVNTRU5USUFMX1BBUkFNRVRFUl9OT1RfRk9VTkQQlU4SEgoNRVJSX0VYQ0VQ",
            "VElPThCWThIOCglzZGZzZGZzZGYQ6gcSDwoJQU5TX0VSUk9SEKCcARIZChNF",
            "UlJfVVNFX0lURU1fRkFJTEVEEKGcASpUCg9Db21tb25TdG9yZVR5cGUSDgoK",
            "U1RPUkVfTk9ORRAAEg0KCVNUT1JFX0FPUxABEg0KCVNUT1JFX2lPUxACEhMK",
            "D1NUT1JFX09ORV9TVE9SRRADKnwKEkNvbW1vbkxhbmd1YWdlVHlwZRIRCg1M",
            "QU5HVUFHRV9OT05FEAASDwoLTEFOR1VBR0VfRU4QChIPCgtMQU5HVUFHRV9L",
            "TxAXEg8KC0xBTkdVQUdFX0pQEBYSDwoLTEFOR1VBR0VfQ0gQBhIPCgtMQU5H",
            "VUFHRV9TUBAiKlUKEkNvbW1vbkdhbWVNb2RlVHlwZRISCg5HQU1FX01PREVf",
            "Tk9ORRAAEhcKE0dBTUVfTU9ERV9BRFZFTlRVUkUQARISCg5HQU1FX01PREVf",
            "RFVFTBACQhgKFGNvbS5mcnV0dGlkaW5vLnByb3RvUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.CommonErrorCode), typeof(global::Common.CommonStoreType), typeof(global::Common.CommonLanguageType), typeof(global::Common.CommonGameModeType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 처리 값에 대한 프로토콜 번호
  /// </summary>
  public enum CommonErrorCode {
    [pbr::OriginalName("ERR_SUCCESS")] ErrSuccess = 0,
    [pbr::OriginalName("ERR_FAILED")] ErrFailed = -1,
    /// <summary>
    /// ( 공통 에러는 모든 응답에서 발생할 수 있다. )
    /// </summary>
    [pbr::OriginalName("ANS_COMMON_ERROR")] AnsCommonError = 10000,
    /// <summary>
    /// 패킷 Load 실패
    /// </summary>
    [pbr::OriginalName("ERR_MESSAGE_LOAD_FAILED")] ErrMessageLoadFailed = 10001,
    /// <summary>
    /// 유효한 패킷 검색 실패
    /// </summary>
    [pbr::OriginalName("ERR_MESSAGE_NOT_FOUND")] ErrMessageNotFound = 10002,
    /// <summary>
    /// 요청한 사용자No가 유효하지 않음
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_USERNO")] ErrInvalidUserno = 10003,
    /// <summary>
    /// 요청한 사용자를 찾을 수 없음
    /// </summary>
    [pbr::OriginalName("ERR_CANNOT_FIND_USER")] ErrCannotFindUser = 10004,
    /// <summary>
    /// 필수 파라미터를 찾을 수 없거나 오류가 발생함
    /// </summary>
    [pbr::OriginalName("ERR_ESSENTIAL_PARAMETER_NOT_FOUND")] ErrEssentialParameterNotFound = 10005,
    /// <summary>
    /// Exception Error 발생
    /// </summary>
    [pbr::OriginalName("ERR_EXCEPTION")] ErrException = 10006,
    /// <summary>
    /// 닉네임 길이 부족
    /// </summary>
    [pbr::OriginalName("sdfsdfsdf")] Sdfsdfsdf = 1002,
    /// <summary>
    /// ( 특정 응답에서만 발생 하는 에러이다.  ※ 각 프로토콜 참조)
    /// </summary>
    [pbr::OriginalName("ANS_ERROR")] AnsError = 20000,
    /// <summary>
    /// 게임 아이템 사용 실패
    /// </summary>
    [pbr::OriginalName("ERR_USE_ITEM_FAILED")] ErrUseItemFailed = 20001,
  }

  /// <summary>
  /// 운영체제
  /// </summary>
  public enum CommonStoreType {
    [pbr::OriginalName("STORE_NONE")] StoreNone = 0,
    [pbr::OriginalName("STORE_AOS")] StoreAos = 1,
    [pbr::OriginalName("STORE_iOS")] StoreIOs = 2,
    [pbr::OriginalName("STORE_ONE_STORE")] StoreOneStore = 3,
  }

  /// <summary>
  /// 언어 (기본 10 영어, 23 한국어, 22 일본어, 6 중국어, 34 스페인어)
  /// </summary>
  public enum CommonLanguageType {
    [pbr::OriginalName("LANGUAGE_NONE")] LanguageNone = 0,
    [pbr::OriginalName("LANGUAGE_EN")] LanguageEn = 10,
    [pbr::OriginalName("LANGUAGE_KO")] LanguageKo = 23,
    [pbr::OriginalName("LANGUAGE_JP")] LanguageJp = 22,
    [pbr::OriginalName("LANGUAGE_CH")] LanguageCh = 6,
    [pbr::OriginalName("LANGUAGE_SP")] LanguageSp = 34,
  }

  public enum CommonGameModeType {
    [pbr::OriginalName("GAME_MODE_NONE")] GameModeNone = 0,
    [pbr::OriginalName("GAME_MODE_ADVENTURE")] GameModeAdventure = 1,
    [pbr::OriginalName("GAME_MODE_DUEL")] GameModeDuel = 2,
  }

  #endregion

}

#endregion Designer generated code
